-- Migration: Create wishlist_impacto33 table with RLS policies
-- Description: Table to store user favorite products with Row Level Security

-- 1) Create the wishlist_impacto33 table
CREATE TABLE IF NOT EXISTS public.wishlist_impacto33 (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  product_id integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wishlist_impacto33_user_id_product_id_key UNIQUE (user_id, product_id)
);

-- 2) Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_wishlist_impacto33_user_id ON public.wishlist_impacto33 (user_id);
CREATE INDEX IF NOT EXISTS idx_wishlist_impacto33_product_id ON public.wishlist_impacto33 (product_id);

-- 3) Enable Row Level Security
ALTER TABLE public.wishlist_impacto33 ENABLE ROW LEVEL SECURITY;

-- 4) Create RLS policies

-- SELECT: Users can only view their own favorites
CREATE POLICY IF NOT EXISTS wishlist_select_own ON public.wishlist_impacto33
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- INSERT: Users can only insert their own favorites
CREATE POLICY IF NOT EXISTS wishlist_insert_own ON public.wishlist_impacto33
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

-- DELETE: Users can only delete their own favorites
CREATE POLICY IF NOT EXISTS wishlist_delete_own ON public.wishlist_impacto33
  FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- Grant permissions to authenticated users
GRANT SELECT, INSERT, DELETE ON public.wishlist_impacto33 TO authenticated;
GRANT USAGE ON SEQUENCE public.wishlist_impacto33_id_seq TO authenticated;
